name: Build and Publish

on:
  # push:
  #   branches:
  #     - master
    pull_request:
  

jobs:
  build-app:
    # permissions:
    #   pages: write
    #   id-token: write
    #   contents: read

    # environment:
    #   name: github-pages
    #   url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: true

      - name: Build App
        run: |
          pnpm build

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bb-rules
          directory: build
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          # Optional: Change the working directory
          # workingDirectory: rules
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'